### PR TITLE
Migrate to Manifest v3

### PR DESCRIPTION
**Pull request by TgSeed**
Hello, I'm not sure if you're active or following github anymore, but i have been using this extension for a long time and it had some issues with latest browser versions (I have only tried in FireFox) which was somehow annoying and i was unable to find such a great extension for my use case anywhere else.
That's why i tried to update and fix the issues.
Thanks for the great extension you built.

Migrate to Manifest v3

* Migrate settings storage to `browser.storage.local`
* Fixes options page on latest browsers
* Fixes non-persistence settings on latest browsers
* Fixes CORS errors on latest browsers

### CODE REVIEW

**Comment by AykutCevik** [comment]
First of all thank you very much for your hard work getting into the code and upgrading it @TgSeed!
>Hello, I'm not sure if you're active or following github anymore

I am, yes. As my other businesses take a lot of time, it will take a while to go through your PR. But it looks great at the first glance!

Can you tell me which problems you had previously which made you create the PR?

**Comment by TgSeed** [comment]
> I am, yes. As my other businesses take a lot of time, it will take a while to go through your PR. But it looks great at the first glance!

Thanks for reviewing it



> Can you tell me which problems you had previously which made you create the PR?

I have been using Cloudflare WARP and that does rotate the IP address, and using your extension i have been getting A LOT of IP change notifications because the extension wasn't saving/keeping the settings.
It was the one and only reason i decided to fork and fix.

**Comment by AykutCevik** [comment]
@TgSeed where you able to run it in current Chrome version? I got several issues including the attached one:
image

**Comment by AykutCevik** [comment]
I migrated to Manifest V3 with the latest release as the deadline was due. Thanks for your previous work @TgSeed 🙏

**Comment by TgSeed** [comment]
> I migrated to Manifest V3 with the latest release as the deadline was due. Thanks for your previous work @TgSeed 🙏

Thanks a lot for updating the extension, I appreciate it.
Can you please update the [Firefox](https://addons.mozilla.org/de/firefox/addon/ip-geolocator/) extension too?

**Comment by AykutCevik** [comment]
@TgSeed Firefox is currently not fully supporting Manifest V3. Once they finish the implementation, I'll migrate to it. As of now, service workers are needed to run the extension, this is lacking in Firefox right now. See here more: https://blog.mozilla.org/addons/2024/03/13/manifest-v3-manifest-v2-march-2024-update/

Firefox doesn't plan to deprecate Manifest V2, so we are safe for now :)

**Pull request closed without merging**
